### ISSUE TITLE
Dark Discord theme covers visualizer

### ISSUE THREAD

**Issue by itsmeboy0** [malte-linke/powercord-pspectrum#2]
I have installed the plugin and I see the executable running, but it doesn't seem to be working. I am running Windows 11 Beta (Maybe related?).

Edit: It is a theme problem and [Dark Discord](https://github.com/snappercord/dark-discord) causes the visualizer to be covered.

**Comment by malte-linke** [comment]
Open your console, by pressing ctrl + I, then disable my plugin and re-enable it.
Take a screenshot of the output and send it here please.

**Comment by itsmeboy0** [comment]
I see now, one of my themes covers the visualizer. I turned off all themes and it appears properly now. Gotta check what theme it is.

**Comment by itsmeboy0** [comment]
[Dark discord](https://github.com/snappercord/dark-discord) is the culprit.

**Comment by malte-linke** [comment]
Sorry for my late response. I totally forgot this...

You can fix that by applying a custom css rule:
```css
#pspectrum-visualizer { z-index: 0 !important; }
```

This is not really a bug as I can't add support for every custom theme.
