### ISSUE TITLE
Visualizer appears to be cut off

### ISSUE THREAD

**Issue by naoei** [malte-linke/powercord-pspectrum#3]
![image](https://user-images.githubusercontent.com/35349837/130367083-6455cf0e-e321-4833-9294-891adaeac41e.png)

I'm not entirely sure where the issue would lie.

**Comment by malte-linke** [comment]
please try reinstalling the plugin by deleting the powercord-pspectrum directory.
I made some changes to the binarys recent, maybe that could cause some errors.

**Comment by malte-linke** [comment]
I can reproduce the bug, a fix is in work

**Comment by naoei** [comment]
Seems to be working wonderfully now.
Thanks!
